const roomsDetails = {
  "Living Room": {
    Room: "Living Room",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 48,
    "Measured Temperature": 30,
    "Measured Humidity": 48,
  },
  "Guest Room": {
    Room: "Guest Room",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 45,
    "Measured Temperature": 20,
    "Measured Humidity": 45,
  },
  "Kitchen Room": {
    Room: "Kitchen Room",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 56,
    "Measured Temperature": 18,
    "Measured Humidity": 56,
  },
  "Master Bedroom": {
    Room: "Master Bedroom",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 52,
    "Measured Temperature": 28,
    "Measured Humidity": 52,
  },
  Library: {
    Room: "Library",
    "isAir ConditionerActive": false,
    isTemperatureActive: false,
    isLightsActive: false,
    isMusicActive: false,
    "Device Temperature": 51,
    "Measured Temperature": 25,
    "Measured Humidity": 51,
  },
};

module.exports = roomsDetails;
